[default]
gym_env_id = 'Pendulum-v1'
batch_size = 200
min_buffer_size = 1000
max_buffer_size = 100000
tau = 0.005
gamma = 0.99
reward_scale = 5

train_episodes = 50
test_episodes = 300

actor_lr = 3e-4
critic_lr = 3e-4
