[default]
gym_env_id = 'Pendulum-v1'
dtype = 'float32'
batch_size = 200
min_buffer_size = 1000
max_buffer_size = 100_000
tau = 0.005
gamma = 0.99
reward_scale = 5

train_episodes = 50
checkpoint_freq = 10

actor_lr = 3e-4
critic_lr = 3e-4

videos_dir = 'videos'

[ant]
gym_env_id = 'Ant-v5'
dtype = 'float64'
batch_size = 256

min_buffer_size = 10_000
max_buffer_size = 1_000_000

train_episodes = 5000
checkpoint_freq = 100


[humanoid]
gym_env_id = 'Humanoid-v5'
dtype = 'float64'
batch_size = 256

min_buffer_size = 10_000
max_buffer_size = 1_000_000

train_episodes = 10000
checkpoint_freq = 100
reward_scale = 20
